plugins {
    id 'java'
    id 'io.spring.dependency-management' version '1.1.7'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.4.2"
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2024.0.0"
    }
}

dependencies {
    // API 응답/컨트롤러 어드바이스, 서블릿 필터 등에서 필요
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // SecurityConfig, JwtAuthenticationFilter 등 인증/인가
    implementation 'org.springframework.boot:spring-boot-starter-security'
    // JwtAuthenticationFilter의 jakarta.validation 어노테이션
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // BaseTimeEntity(@MappedSuperclass), JpaAuditingConfig
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // ApiControllerAdvice의 FeignException 처리
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
